-- Agregar columnas faltantes a la tabla horario
ALTER TABLE horario ADD COLUMN IF NOT EXISTS activo TINYINT(1) DEFAULT 1;
ALTER TABLE horario ADD COLUMN IF NOT EXISTS fecha_inicio DATE DEFAULT CURDATE();
ALTER TABLE horario ADD COLUMN IF NOT EXISTS fecha_fin DATE DEFAULT DATE_ADD(CURDATE(), INTERVAL 1 YEAR);
